---
version: '3.7'
services:
  logpiped:
    image: cachecash/go-cachecash
    build: .
    command: logpiped -spooldir /var/spool/logpiped -esconfig /config/esconfig.json test
    environment:
    - CACHECASH_INSECURE=true
    ports:
    - 9005:9005
    volumes:
    - ./data/logpiped:/var/spool/logpiped
    - ./testdata/config:/config

  ledger:
    image: cachecash/go-cachecash
    build: .
    command: ledgerd -logLevel debug -logAddress logpiped:9005
    ports:
    - 7778:7778  # Ledger service
    - 9091:8100  # Status
    environment:
    - CACHECASH_INSECURE=true
    - LEDGER_DATABASE=host=ledger-db port=5432 user=postgres dbname=ledger sslmode=disable

  ledger-db:
    image: postgres:11
    ports:
    - 5433:5432
    environment:
    - POSTGRES_DB=ledger

  upstream:
    image: nginx
    ports:
    - 8081:80
    volumes:
    - ./testdata/content:/usr/share/nginx/html

  upstream-apache:
    image: httpd
    ports:
    - 8091:80
    volumes:
    - ./testdata/content:/usr/local/apache2/htdocs

  upstream-lighttpd:
    build: deploy/httpds/lighttpd
    ports:
    - 8092:80
    volumes:
    - ./testdata/content:/var/www/localhost/htdocs

  upstream-caddy:
    build: deploy/httpds/caddy
    ports:
    - 8093:80
    volumes:
    - ./testdata/content:/var/www

  upstream-python:
    image: python:3-alpine
    command: python -m http.server -d /var/www 80
    init: true
    ports:
    - 8094:80
    volumes:
    - ./testdata/content:/var/www

  publisher:
    image: cachecash/go-cachecash
    build: .
    command: publisherd -logLevel debug -trace http://jaeger:14268 -logAddress logpiped:9005
    ports:
    - 7070:7070
    - 8043:8043
    # status
    - 8100:8100
    environment:
    - CACHECASH_INSECURE=true
    - PUBLISHER_PUBLISHER_ADDR=publisher:7070
    - PUBLISHER_UPSTREAM=${PUBLISHER_UPSTREAM:-http://upstream:80}
    - PUBLISHER_BOOTSTRAP_ADDR=bootstrapd:7777
    - PUBLISHER_DATABASE=host=publisher-db port=5432 user=postgres dbname=publisher sslmode=disable
    volumes:
    - ./data/publisher:/data

  publisher-db:
    image: postgres:11
    ports:
    - 5434:5432
    environment:
    - POSTGRES_DB=publisher

  bootstrapd:
    image: cachecash/go-cachecash
    build: .
    command: bootstrapd -logLevel debug -trace http://jaeger:14268 -logAddress logpiped:9005
    environment:
    - CACHECASH_INSECURE=true
    ports:
    - 7777:7777
    # status
    - 8101:8100
    volumes:
    - ./data/bootstrapd:/data

  cache-0:
    image: cachecash/go-cachecash
    build: .
    command: cached -logLevel debug -trace http://jaeger:14268 -logAddress logpiped:9005
    ports:
    - 9000:9000
    - 9443:9443
    # status
    - 7100:9100
    environment:
    - CACHECASH_INSECURE=true
    - CACHE_BOOTSTRAP_ADDR=bootstrapd:7777
    - CACHE_METRICS_ENDPOINT=metrics:8000
    volumes:
    - ./data/cache-0:/data

  cache-1:
    image: cachecash/go-cachecash
    build: .
    command: cached -logLevel debug -trace http://jaeger:14268 -logAddress logpiped:9005
    ports:
    - 9001:9000
    - 9444:9443
    # status
    - 7101:9100
    environment:
    - CACHECASH_INSECURE=true
    - CACHE_BOOTSTRAP_ADDR=bootstrapd:7777
    - CACHE_METRICS_ENDPOINT=metrics:8000
    volumes:
    - ./data/cache-1:/data

  cache-2:
    image: cachecash/go-cachecash
    build: .
    command: cached -logLevel debug -trace http://jaeger:14268 -logAddress logpiped:9005
    ports:
    - 9002:9000
    - 9445:9443
    # status
    - 7102:9100
    environment:
    - CACHECASH_INSECURE=true
    - CACHE_BOOTSTRAP_ADDR=bootstrapd:7777
    - CACHE_METRICS_ENDPOINT=metrics:8000
    volumes:
    - ./data/cache-2:/data

  cache-3:
    image: cachecash/go-cachecash
    build: .
    command: cached -logLevel debug -trace http://jaeger:14268 -logAddress logpiped:9005
    ports:
    - 9003:9000
    - 9446:9443
    - 7103:9100
    environment:
    - CACHECASH_INSECURE=true
    - CACHE_BOOTSTRAP_ADDR=bootstrapd:7777
    - CACHE_METRICS_ENDPOINT=metrics:8000
    volumes:
    - ./data/cache-3:/data

  cache-4:
    image: cachecash/go-cachecash
    build: .
    command: cached -logLevel debug -trace http://jaeger:14268 -logAddress logpiped:9005
    ports:
    - 9004:9000
    - 9447:9443
    # status
    - 7104:9100
    environment:
    - CACHECASH_INSECURE=true
    - CACHE_BOOTSTRAP_ADDR=bootstrapd:7777
    - CACHE_METRICS_ENDPOINT=metrics:8000
    volumes:
    - ./data/cache-4:/data

  jaeger:
    image: jaegertracing/all-in-one:1.8
    ports:
    - 5775:5775/udp
    - 6831:6831/udp
    - 6832:6832/udp
    - 5778:5778
    # UI
    - 16686:16686
    - 14268:14268
    - 9411:9411

  elasticsearch:
    image: elasticsearch:7.3.0
    ports:
    - 9200:9200
    - 9300:9300
    environment:
    - discovery.type=single-node

  kibana:
    image: kibana:7.3.0
    ports:
    - 5601:5601

  metrics:
    image: cachecash/go-cachecash
    build: .
    command: metrics-proxy -logLevel debug -trace http://jaeger:14268
    environment:
    - CACHECASH_INSECURE=true
    ports:
    - 8000:8000
    - 8102:8100


...
